{{- if .Values.initializationFilesFromFs -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-initialization
data:
{{- if .Values.initializationFilesFromFs -}}
  {{- $file := .Files }}
  {{- $dbuser := .Values.celleryDbUser }}
  {{- $dbpassword := .Values.celleryDbPassword }}
  {{- range $path, $byte := .Files.Glob "confs/init.sql" }}
  {{- $list := $path | splitList "/"}}
  {{- $length := len $list }}
  {{- $last := add $length -1 }}
  {{ index $list $last }}: |-
    {{- range $line := $file.Lines $path }}
    {{ $line | replace "DATABASE_USERNAME" $dbuser | replace "DATABASE_PASSWORD" $dbpassword }}
    {{- end }}
  {{- end }}
{{- else -}}
{{- range $key, $val := .Values.initializationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}
{{- end -}}
